### ISSUE TITLE
What does ksv's patch do?

### ISSUE THREAD

**Issue by alexose** [BurntSushi/rtmpdump-ksv#2]
A short explanation in the README would be helpful :)

**Comment by BurntSushi** [comment]
I have no idea what it does unfortunately. All I really know is that `rtmpdump` didn't work on a particular video stream and `rtmpdump` with "ksv's patch" does. Some digging with google might lead to some explanation. Sorry I couldn't be of more help!

**Comment by chopraaa** [comment]
Minor fixes and additions like resume support. Note that KSV's first patch came out in 2013. So it's basic.
