### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by broguebart** [BurntSushi/rtmpdump-ksv#4]
Can someone please guide me on how to get the ksv version of rtmpdump to work/install on Debian/Ubuntu as I can't find any installation guide. I am only able to install up to rtmpdump without the KSV Patch. Thanks

**Comment by BurntSushi** [comment]
> I can't find any installation guide

The [README](https://github.com/BurntSushi/rtmpdump-ksv/blob/ksv/README) is a good place to start.................

**Comment by broguebart** [comment]
I tried following the Readme but the official problem is that I need to know how to patch rtmpdump under debian with the KSV patch since another script i'm running uses rtmpdump and I am not going to be using it directly. I just need help on how to patch my rtmpdump version with the KSV patch... thanks for your help I am using Debian

**Comment by BurntSushi** [comment]
Uninstall the debian `rtmpdump` package, compile this one and put it in your `PATH`?

I don't use Debian. Sorry, but you're on your own.

**Comment by alpinesound** [comment]
(
