### ISSUE TITLE
'openssl/ssl.h' file not found

### ISSUE THREAD

**Issue by kuca2002** [BurntSushi/rtmpdump-ksv#5]
im on mac osx 10.12.6
when i type in make SYS=mingw or make SHARED=mingw it brings this error message:

`gcc -Wall   -DRTMPDUMP_VERSION=\"v2.4\" -DUSE_OPENSSL  -O2 -fPIC   -c -o rtmp.o rtmp.c
rtmp.c:61:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [rtmp.o] Error 1
make: *** [librtmp/librtmp.a] Error 2`

how can i fix this, i also tried with sudo

**Comment by BurntSushi** [comment]
I can't help you beyond what is in the readme. I didn't write this code and don't use a mac.

**Comment by kuca2002** [comment]
mmmm who should i contact to get help?

**Comment by BurntSushi** [comment]
I just told you that I didn't write this code and that I can't help you. Look at the README.
